print("""
 ░▒▓██████▓▒░░▒▓███████▓▒░░▒▓███████▓▒░░▒▓█▓▒░▒▓███████▓▒░  
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓███████▓▒░  
░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
 ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
                                                            
                                                            
CrDir - Create folders, then cd into them.
Made by Ghosty

""")

import subprocess
import os


folderNm = input("Name of the folder to create: ").strip()

if not folderNm:
    print("Folder name cannot be empty.")
    exit(1)

# Crear la carpeta si no existe
os.makedirs(folderNm, exist_ok=True)

# Crear el script .sh que se autoejecuta y se borra
script_name = "cd_into_folder.sh"
script_content = f"""#!/bin/bash
# Auto-generated by CrDir
cd "{folderNm}"
rm -- ../"$0"
exec $SHELL
"""

with open(script_name, "w") as f:
    f.write(script_content)

os.chmod(script_name, 0o755)

# Ejecutar el script (esto abre subshell dentro de la carpeta y se borra solo)
subprocess.run([f"./{script_name}"])
